version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - nebula_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Inventario Microservice
  inventario:
    build:
      context: .
      dockerfile: apps/inventario/Dockerfile
    command: sh /app/entrypoint.sh 0.0.0.0:8000
    volumes:
      - .:/app
      - ./firebase:/app/firebase
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nebula_network

  # Informacion Microservice
  informacion:
    build:
      context: .
      dockerfile: apps/informacion/Dockerfile
    command: sh /app/entrypoint.sh 0.0.0.0:8001
    volumes:
      - .:/app
      - ./firebase:/app/firebase
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nebula_network

  # Usuarios y Roles Microservice
  usuarios_roles:
    build:
      context: .
      dockerfile: apps/usuarios_roles/Dockerfile
    command: sh /app/entrypoint.sh 0.0.0.0:8002
    volumes:
      - .:/app
      - ./firebase:/app/firebase
    ports:
      - "8002:8002"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nebula_network

volumes:
  postgres_data:

networks:
  nebula_network:
    driver: bridge
